compiler: g++-7
dist: trusty
language: cpp

addons:
  apt:
    packages:
      - g++-7
      - libmariadbclient-dev
    sources:
      - ubuntu-toolchain-r-test
  mariadb: 10.3

env:
  global:
    - BUILD_DIR=$TRAVIS_BUILD_DIR/build
    - PREMAKE_DIR=$TRAVIS_BUILD_DIR/premake
    - SCRIPTS_DIR=$TRAVIS_BUILD_DIR/scripts
  matrix:
    - CONFIGURATION=Debug
    - CONFIGURATION=Release

git:
  depth: 1

before_script:
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-linux.tar.gz
  - tar xzf premake-*-linux.tar.gz -C ${PREMAKE_DIR}

  - mysql -e "CREATE USER 'dodbm'@'127.0.0.1' IDENTIFIED BY 'do';" --user=root
  - mysql -e "CREATE DATABASE dodbm;" --user=root
  - mysql -e "GRANT ALL PRIVILEGES ON `dodbm`.* TO 'dodbm'@'127.0.0.1';" --user=root

script:
  - cd ${PREMAKE_DIR}
  - chmod +x ./generate_gmake_projects.sh
  - ./generate_gmake_projects.sh
  - cd projects
  - make config=${CONFIGURATION,,} CXX=g++-7
  - cd ${SCRIPTS_DIR}
  - chmod +x ./run_tests.sh
  - ./run_tests.sh ${BUILD_DIR}/${CONFIGURATION,,}/bin