compiler: g++-7
dist: trusty
language: cpp

addons:
  apt:
    packages:
      - g++-7
      - libmariadbclient-dev
    sources:
      - ubuntu-toolchain-r-test
  mariadb: 10.3

env:
  global:
    - BUILD_DIR=$TRAVIS_BUILD_DIR/build
    - SCRIPTS_DIR=$TRAVIS_BUILD_DIR/scripts
  matrix:
    - CONFIGURATION=Debug
    - CONFIGURATION=Release

git:
  depth: 1

before_script:
  - mysql -e "CREATE USER 'dodbm'@'%' IDENTIFIED BY 'do';" --user=root
  - mysql -e "CREATE DATABASE dodbm;" --user=root
  - mysql -e "GRANT ALL PRIVILEGES ON dodbm.* TO 'dodbm'@'%';" --user=root

  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${CONFIGURATION}

script:
  - cmake --build . --config ${CONFIGURATION}
  - cd ${SCRIPTS_DIR}
  - chmod +x ./run_tests.sh
  - ./run_tests.sh ${BUILD_DIR}/${CONFIGURATION,,}/bin