clone_depth: 1
image: Visual Studio 2017
version: '{branch}.{build}'

build:
  verbosity: minimal

configuration:
  - Debug
  - Release

environment:
  bin_dir: $(APPVEYOR_BUILD_FOLDER)/build/$(configuration)/bin
  premake_dir: $(APPVEYOR_BUILD_FOLDER)/premake
  scripts_dir: $(APPVEYOR_BUILD_FOLDER)/scripts

platform:
  - x64

pull_requests:
  do_not_increment_build_number: true

install:
  - git submodule update --init --recursive
  - ps: appveyor DownloadFile https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-windows.zip
  - ps: 7z e premake-*-windows.zip -o"$env:premake_dir"

  - ps: appveyor DownloadFile https://downloads.mariadb.com/Connectors/c/connector-c-3.0.6/mariadb-connector-c-3.0.6-win64.msi
  - ps: msiexec /i mariadb-connector-c-3.0.6-win64.msi /quiet /qn -L*V ./log.txt
  - ps: Remove-Item mariadb-connector-c-3.0.6-win64.msi
  - ps: Get-Content -Path ./log.txt

before_build:
  - ps: cd $env:premake_dir
  - ps: ./generate_vs_projects.bat

test_script:
  - ps: cd "$env:scripts_dir"
  - ps: ./run_tests.ps1 $env:bin_dir

artifacts:
  - path: build/$(configuration)/libs
    name: dodbm
    type: zip