clone_depth: 1
image: Visual Studio 2017
version: '{branch}.{build}'

build:
  verbosity: minimal

configuration:
  - Debug
  - Release

environment:
  bin_dir: $(APPVEYOR_BUILD_FOLDER)/build/$(configuration)/bin
  scripts_dir: $(APPVEYOR_BUILD_FOLDER)/scripts

platform:
  - x64

pull_requests:
  do_not_increment_build_number: true

services:
  - mysql

install:
  - cmd: git submodule update --init --recursive

  - ps: appveyor DownloadFile https://downloads.mariadb.com/Connectors/c/connector-c-3.0.6/mariadb-connector-c-3.0.6-win64.msi
  - cmd: msiexec /i mariadb-connector-c-3.0.6-win64.msi /quiet /qn
  - ps: Remove-Item mariadb-connector-c-3.0.6-win64.msi

  - ps: $env:PATH += ";C:\Program Files\MariaDB\MariaDB Connector C 64-bit\lib"
  - ps: $env:PATH += ";C:\Program Files\MySql\MySQL Server 5.7\bin"

before_build:
  - ps: mkdir build
  - ps: cd build
  - ps: cmake .. -DCMAKE_BUILD_TYPE=${CONFIGURATION}

before_test:
  - cmd: mysql -e "CREATE USER 'dodbm'@'%' IDENTIFIED BY 'do';" --user=root --password=Password12!
  - cmd: mysql -e "CREATE DATABASE dodbm;" --user=root --password=Password12!
  - cmd: mysql -e "GRANT ALL PRIVILEGES ON dodbm.* TO 'dodbm'@'%';" --user=root --password=Password12!

test_script:
  - ps: cd "$env:scripts_dir"
  - ps: ./run_tests.ps1 $env:bin_dir

artifacts:
  - path: build/$(configuration)/libs
    name: dodbm
    type: zip